config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resource :accounts
  resources :plans, only: [:index, :show]
  resources :subscriptions, only: [:create, :destroy]
  resources :cards, only: [:create]
  resources :billing, only: [:index] do
    collection do
      get 'change_card'
    end
  end
  resources :integrations, only: [:index] do
    collection do
      delete ':provider', action: 'destroy', as: 'remove'
    end
  end

  get 't/new', to: 'teams#new'
  get 't/:id/edit', to: 'teams#edit'
  get 't/:id/s', to: 'teams#standups', as: 'team_standups'
  get 't/:id/s/(:date)', to: 'teams#standups', as: 'team_standups_by_date'
  get 't/:id/(:date)', to: 'teams#show'
  resources :teams, path: 't'

  get 's/new/(:date)', to: 'standups#new', as: 'new_standup'
  get 's/edit/(:date)', to: 'standups#edit', as: 'edit_standup'
  resources :standups, path: 's', except: [:new, :edit]

  get 'user/me', to: 'users#me', as: 'my_settings'
  patch 'users/update_me', to: 'users#update_me', as: 'update_my_settings'
  get 'user/password', to: 'users#password', as: 'my_password'
  patch 'user/update_password', to: 'users#update_password', as: 'my_update_password'

  scope 'account', as: 'account' do
    resources :plans, only: [:index, :show], controller: 'accounts/plans'
    resources :users do
      member do
        get 's', to: 'users#standups', as: 'standups'
        get 's/(p/:page)', action: :standups
      end
    end
  end

  get 'activity/mine'
  get 'activity/mine/(p/:page)', to: 'activity#mine'

  get 'activity/feed'

  get 'dates/:date', to: 'dates#update', as: 'update_date'

  require "sidekiq/web"
  require 'sidekiq/cron/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest(ENV["SK_USER"])
    ) &
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(password),
      ::Digest::SHA256.hexdigest(ENV["SK_PASS"])
    )
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  # mount using default path: /email_processor
  mount_griddler

  mount StripeEvent::Engine, at: '/billing/events'

  # Webhooks
  post 'integrations/github/webhook/:team_id', to: 'events/github#create'

  root to: 'activity#mine'
end

app/models/standup.rb
class Standup < ApplicationRecord
  include Friendlyable
  belongs_to :user

  validates :user, presence: true

  validates :standup_date, uniqueness: { scope: :user }

  has_many :task_memberships, dependent: :delete_all
  has_many :tasks, through: :task_memberships

  has_many :dids,
           -> { where(type: 'Did') },
           through: :task_memberships,
           source: :task
  accepts_nested_attributes_for :dids,
                                reject_if: :all_blank,
                                allow_destroy: true

  has_many :todos,
           -> { where(type: 'Todo') },
           through: :task_memberships,
           source: :task
  accepts_nested_attributes_for :todos,
                                reject_if: :all_blank,
                                allow_destroy: true

  has_many :blockers,
           -> { where(type: 'Blocker') },
           through: :task_memberships,
           source: :task
  accepts_nested_attributes_for :blockers,
                                reject_if: :all_blank,
                                allow_destroy: true
end

app/controllers/standups_controller.rb
class StandupsController < ApplicationController
  before_action :set_standup, only: [:show, :update, :destroy]

  def index
    redirect_to(root_path)
  end

  # GET /standups/1
  # GET /standups/1.json
  def show
  end

  # GET /standups/new
  def new
    return if check_for_blank_date
    return if check_for_existance
    @standup = Standup.new
  end

  # GET /standups/1/edit
  def edit
    return if check_for_blank_date
    return if check_for_existance
    @standup = Standup.find_by(
      user_id: current_user.id,
      standup_date: current_date
    )
  end

  # POST /standups
  # POST /standups.json
  def create
    @standup = Standup.new(standup_params)
    @standup.user = current_user

    if @standup.save
      invoke_cables
      redirect_back(
        fallback_location: root_path,
        notice: 'Standup was successfully created.'
      )
    else
      render :new
    end
  end

  # PATCH/PUT /standups/1
  # PATCH/PUT /standups/1.json
  def update
    if @standup.update(standup_params)
      invoke_cables
      redirect_back(
        fallback_location: root_path,
        notice: 'Standup was successfully updated.'
      )
    end
  end

  # DELETE /standups/1
  # DELETE /standups/1.json
  def destroy
    @standup.destroy
    respond_to do |format|
      format.html { redirect_to standups_url, notice: 'Standup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_standup
    @standup = Standup.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def standup_params
    params.require(:standup).permit(:standup_date, dids_attributes: [:id, :title, :_destroy], todos_attributes: [:id, :title, :_destroy], blockers_attributes: [:id, :title, :_destroy])
  end

  def check_for_blank_date
    if params[:date].blank?
      redirect_to(
        update_date_path(
          date: Date.today.iso8601,
          reload_path: "/s/#{action_name}/#{Date.today.iso8601}"
        )
      ) and return true
    end
  end

  def check_for_existance
    standup = Standup.find_by(user_id: current_user.id, standup_date: current_date)
    if standup.present? && action_name == 'new'
      redirect_to(edit_standup_path(date: current_date)) and return true
    elsif standup.nil? && action_name == 'edit'
      redirect_to(new_standup_path(date: current_date)) and return true
    end
  end

  def invoke_cables
    CableServices::NotifyJobsService.(
      standup: @standup,
      action: action_name.to_sym,
      user: current_user
    )
  end
end

app/helpers/standups_helper.rb
module StandupsHelper
  def notification_standups(user)
    user
      .teams
      .flat_map do |t|
        t.users.flat_map do |u|
          u.standups.order(created_at: :desc).limit(10)
        end
      end
      .sort_by(&:created_at)
      .reverse[0..9]
  end
end

app/views/standups/_blocker_fields.html.slim
.nested-fields.input-group
  = f.text_field :title, class: 'form-control input-lg',\
  placeholder: 'Something impeding me'
  span.input-group-addon
    = link_to_remove_association f do
      .fa.fa-trash

app/views/standups/_did_fields.html.slim
.nested-fields.input-group
  = f.text_field :title, class: 'form-control input-lg',\
    placeholder: 'A thing I did'
  span.input-group-addon
    = link_to_remove_association f do
      .fa.fa-trash

app/views/standups/_form.html.slim
= form_for @standup do |f|
  = f.hidden_field :standup_date, value: current_date
  - if @standup.errors.any?
    = render partial: 'shared/model_errors', locals: {model: @standup}
  = render partial: 'layouts/date_change', locals:\
    {reload_path: "/s/#{action_name}"}
  .row
    .col-sm-8.col-sm-offset-2
      .box
        .box-header
          h3 What did you do since your last standup?
        .box-body
          = f.fields_for :dids do |did|
            = render 'did_fields', f: did
          .links
            = link_to_add_association f, :dids, class: 'btn btn-sm bg-olive',\
              style: 'border-radius:50%' do
                i.fa.fa-plus
  .row
    .col-sm-8.col-sm-offset-2
      .box
        .box-header
          h3 What are you doing today?
        .box-body
          = f.fields_for :todos do |todo|
            = render 'todo_fields', f: todo
          .links
            = link_to_add_association f, :todos, class: 'btn btn-sm bg-olive',\
              style: 'border-radius:50%' do
                i.fa.fa-plus
  .row
    .col-sm-8.col-sm-offset-2
      .box
        .box-header
          h3 What is blocking you?
        .box-body
          = f.fields_for :blockers do |blocker|
            = render 'blocker_fields', f: blocker
          .links
            = link_to_add_association f, :blockers,\
              class: 'btn btn-sm bg-olive',\
              style: 'border-radius:50%' do
                i.fa.fa-plus

  .row
    .col-sm-8.col-sm-offset-2
      = f.submit 'Save', class: ' btn btn-primary'

app/views/standups/_standup.html.slim
.box-body
  h4
    | Dids
    ul.todo-list
      - standup.dids.each do |did|
        li= did.title
  h4
    | Todos
    ul.todo-list
      - standup.todos.each do |todo|
        li= todo.title
  h4
    | Blockers
    ul.todo-list
      - standup.blockers.each do |blocker|
        li= blocker.title

app/views/standups/_todo_fields.html.slim
.nested-fields.input-group
  = f.text_field :title, class: 'form-control input-lg',\
    placeholder: 'A thing I am doing'
  span.input-group-addon
    = link_to_remove_association f do
      .fa.fa-trash

app/views/standups/edit.html.slim
.content-header
  h2 Update your Standup

.content
  = render 'form'

app/views/standups/new.html.slim
.content-header
  h2 Add a Standup

.content
  = render 'form'

app/views/standups/show.html.slim
p#notice = notice

p
  strong User:
  = @standup.user
p
  strong Standup date:
  = @standup.standup_date

= link_to 'Edit', edit_standup_path(@standup)
'  |
= link_to 'Back', standups_path