config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resource :accounts
  resources :plans, only: [:index, :show]
  resources :subscriptions, only: [:create, :destroy]
  resources :cards, only: [:create]
  resources :billing, only: [:index] do
    collection do
      get 'change_card'
    end
  end
  resources :integrations, only: [:index] do
    collection do
      delete ':provider', action: 'destroy', as: 'remove'
    end
  end

  get 't/new', to: 'teams#new'
  get 't/:id/edit', to: 'teams#edit'
  get 't/:id/s', to: 'teams#standups', as: 'team_standups'
  get 't/:id/s/(:date)', to: 'teams#standups', as: 'team_standups_by_date'
  get 't/:id/(:date)', to: 'teams#show'
  resources :teams, path: 't'

  get 's/new/(:date)', to: 'standups#new', as: 'new_standup'
  get 's/edit/(:date)', to: 'standups#edit', as: 'edit_standup'
  resources :standups, path: 's', except: [:new, :edit]

  get 'user/me', to: 'users#me', as: 'my_settings'
  patch 'users/update_me', to: 'users#update_me', as: 'update_my_settings'
  get 'user/password', to: 'users#password', as: 'my_password'
  patch 'user/update_password', to: 'users#update_password', as: 'my_update_password'

  scope 'account', as: 'account' do
    resources :plans, only: [:index, :show], controller: 'accounts/plans'
    resources :users do
      member do
        get 's', to: 'users#standups', as: 'standups'
        get 's/(p/:page)', action: :standups
      end
    end
  end

  get 'activity/mine'
  get 'activity/mine/(p/:page)', to: 'activity#mine'

  get 'activity/feed'

  get 'dates/:date', to: 'dates#update', as: 'update_date'

  require "sidekiq/web"
  require 'sidekiq/cron/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest(ENV["SK_USER"])
    ) &
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(password),
      ::Digest::SHA256.hexdigest(ENV["SK_PASS"])
    )
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  # mount using default path: /email_processor
  mount_griddler

  mount StripeEvent::Engine, at: '/billing/events'

  # Webhooks
  post 'integrations/github/webhook/:team_id', to: 'events/github#create'

  root to: 'activity#mine'
end

app/models/user.rb
class User < ApplicationRecord
  include Friendlyable
  rolify
  attr_accessor :role
  belongs_to :account
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:github]
  has_many :team_memberships
  has_many :teams, through: :team_memberships
  has_many :standups

  def after_database_authentication
    Analytics::Mixpanel::IdentifyPersonJob.perform_later(self)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github
    @auth = request.env['omniauth.auth']
    if successful_integration_creation
      redirect_to(
        integrations_path,
        notice: 'Github integration has been added'
      )
    else
      redirect_to(
        integrations_path,
        alert: "Github was unable to add integration.\
Contact support if this issue persists."
      )
    end
  end

  private

  def create_github_integration
    Integrations::Github.create!(
      account_id: current_account.id,
      settings: {
        token: @auth.credentials.token
      }
    )
  end

  def successful_integration_creation
    @auth != :invalid_credentials &&
      @auth&.credentials&.token &&
      create_github_integration
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Limits
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:index]
  load_and_authorize_resource :find_by => :hash_id

  def index

  end

  def new
    @user = User.new
    set_choices
  end

  def edit
    set_choices
  end

  def standups
    @user =
      User
      .friendly
      .find(params[:id])
    @standups =
      @user
      .standups
      .includes(:dids, :todos, :blockers)
      .references(:tasks)
      .order('standup_date DESC')
      .page(params[:page])
      .per(6)
  end

  def me
    @user = current_user
  end

  def password
    @user = current_user
  end

  def update_password
    @user = current_user
    respond_to do |format|
      if @user.update(user_password_params)
        bypass_sign_in(@user)
        format.html { redirect_to my_password_path, notice: 'Password was successfully updated.' }
      else
        format.html { render :password }
      end
    end
  end

  def update_me
    @user = current_user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to my_settings_path, notice: 'Your information was successfully updated.' }
      else
        format.html { render :me }
      end
    end
  end

  # POST /account/users
  # POST /account/users.json
  def create
    check_resource_against_limits(:users) do
      return redirect_back(
        fallback_location: root_path,
        notice: "You do not have the resources to create this User,\
 please consider upgrading your plan."
      )
    end

    @user = User.unscoped.new(user_params.except("role"))
    @user.account = current_account
    @user.password = "password123"

    respond_to do |format|
      begin
        if @user.valid? &&  @user.invite!(current_user)
          @user.add_role user_params[:role].to_sym, current_account
          format.html { redirect_to account_users_path, notice: 'User was successfully invited.' }
        else
          set_choices
          format.html { render :new }
        end
      rescue ActiveRecord::RecordNotUnique
        flash[:alert]= 'Email must be unique'
        format.html { render :new}
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params.except('role'))
        format.html { redirect_to account_users_path, notice: 'User was successfully updated.' }
      else
        set_choices
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to account_users_path, notice: 'User was successfully destroyed.' }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_users
      @users = current_account.users
    end

    def set_user
      @user = User.friendly.find(params[:id])
    end

    def set_choices
      @choices = []
      @choices << ["Admin", 'admin']
      @choices << ["User", 'user']
      @choices
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :role, :time_zone)
    end

    def user_password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_standups.html.slim
- if standups.empty?
  .row
    .col-sm-12
      p No standups are available to display
- standups.each_slice(3) do |sliced_standups|
  .row
    - sliced_standups.each do |standup|
      .col-sm-4
        .box.box-primary.standup-box data={standup: standup.hash_id}
          .box-header.with-border
            h3.box-title= standup.standup_date
          = render partial: 'standups/standup', locals: {standup: standup}
.row
  .col-sm-12
    = paginate standups

app/views/users/edit.html.slim
.content-header
  h2 Users
.content
  .row
    .col-lg-12
        .box.box-primary
          = form_for(@user, url: account_user_path(@user), html: {class: 'form-horizontal'}) do |f|
            .box-header
              h3.box-title 
                | Edit User Information
            .box-body
              -if @user.errors.any?
                .alert.alert-error.alert-block.alert-fixed
                  h4= "#{pluralize(@user.errors.count, "error")} prohibited the user from being saved:"
                  == @user.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
              .form-group
                = f.label :name, class: 'control-label col-lg-2'
                .col-lg-10
                  = f.text_field :name, {placeholder: "Name", autofocus: true, class: "form-control"}
              .form-group
                = f.label :email, class: 'control-label col-lg-2'
                .col-lg-10
                  = f.email_field :email, {placeholder: "Email Address", autofocus: true, class: "form-control"}
              .form-group
                = label_tag "user[role]", "Role", class: 'control-label col-lg-2'
                .col-lg-10
                  = select_tag "user[role]", options_for_select(@choices, @user.roles.first.name), class: 'form-control'
            .box-footer style="height: 55px;"
              span.pull-right    
                = f.submit "Edit User", class: "btn btn-primary"

app/views/users/index.html.slim
.content-header
  h2 Users
.content
  .row
    .col-lg-12
      .box.box-primary
        .box-header
          h3.box-title
            = "Users in #{current_account.name}"
        .box-body
          .table-responsive
            table.table.table-striped
              thead
                tr
                  th Name
                  th Email
                  th Status
                  th Role
                  th Added at
                  th 
              tbody
                - @users.each do |user|
                  tr
                    td= user.name
                    td= user.email
                    td= user.accepted_or_not_invited? ? "Active" : "Invited"
                    td= user.roles&.first&.name&.capitalize
                    td= user.created_at.strftime('%D')
                    td
                      = link_to 'Edit', edit_account_user_path(user), class: 'btn btn-default btn-xs'
                      = link_to 'Destroy', account_user_path(user), {method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning btn-xs'} unless user.id == current_user.id

        .box-footer style="height: 55px;"
          span.pull-right
            a.btn.btn-primary href="#{new_account_user_path}" 
              | Add User                

app/views/users/me.slim
.content-header
  h2 Settings
.content
  .row
    .col-lg-12
        .box.box-primary
          = form_for(@user, url: update_my_settings_path, html:{class: 'form-horizontal'}) do |f|
            .box-header
              h3.box-title My Information
            .box-body
              -if @user.errors.any?
                .alert.alert-error.alert-block.alert-fixed
                  h4= "#{pluralize(@user.errors.count, "error")} prohibited your information from being saved:"
                  == @user.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
              .form-group
                = f.label :name, class: 'control-label col-lg-2'
                .col-lg-10
                  = f.text_field :name, {placeholder: "Name", autofocus: true, class: "form-control"}
              .form-group
                = f.label :email, class: 'control-label col-lg-2'
                .col-lg-10
                  = f.email_field :email, {placeholder: "Email Address", autofocus: true, class: "form-control"}
              .form-group
                = f.label :time_zone, class: 'control-label col-lg-2'
                .col-lg-10
                  = f.time_zone_select(:time_zone, ActiveSupport::TimeZone.us_zones, {}, {class: 'form-control'})
            .box-footer
              .pull-right
                = f.submit "Update My Settings", class: "btn btn-primary"

app/views/users/new.html.slim
.content-header
  h2 Users
.content
  .row
    .col-lg-12
      .box.box-primary
        = form_for(@user, url: account_users_path, html: {class: 'form-horizontal'}) do |f|
          .box-header
            h3.box-title New User Information
          .box-body
              -if @user.errors.any?
                .alert.alert-error.alert-block.alert-fixed
                  h4= "#{pluralize(@user.errors.count, "error")} prohibited your the user from being saved:"
                  == @user.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
              .form-group
                = label_tag "user[name]", "Name", class: 'control-label col-lg-2'
                .col-lg-10
                  = f.text_field :name, {placeholder: "Name", autofocus: true, class: "form-control"}
              .form-group
                = label_tag "user[email]", "Email", class: 'control-label col-lg-2'
                .col-lg-10
                  = f.email_field :email, {placeholder: "Email Address", autofocus: true, class: "form-control"}
              .form-group
                = label_tag "user[role]", "Role", class: 'control-label col-lg-2'
                .col-lg-10
                  = select_tag "user[role]", options_for_select(@choices, 'user'), class: 'form-control'
          .box-footer style="height: 55px;"
            span.pull-right    
              = f.submit "Add User", class: "btn btn-primary"

app/views/users/password.slim
.content-header
  h2 Settings
.content
  .row
    .col-lg-12
        .box.box-primary
           = form_for(@user, url: my_update_password_path, html:{class: 'form-horizontal'}) do |f|
            .box-header
              h3.box-title Update Password
            .box-body
              -if @user.errors.any?
                .alert.alert-error.alert-block.alert-fixed
                  h4= "#{pluralize(@user.errors.count, "error")} prohibited your information from being saved:"
                  == @user.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
              .form-group
                = f.label :password, class: 'control-label col-lg-2'
                .col-lg-10
                  = f.password_field :password, {placeholder: "Enter New Password", autofocus: true, class: "form-control"}
              .form-group
                = f.label :password_confirmation, class: 'control-label col-lg-2'
                .col-lg-10
                  = f.password_field :password_confirmation, {placeholder: "Re-enter New Password", autofocus: true, class: "form-control"}
            .box-footer
              .pull-right
                = f.submit "Update My Password", class: "btn btn-primary"

app/views/users/show.html.slim
h1 Users#show
p Find me in app/views/users/show.html.slim

app/views/users/standups.html.slim
.content-header
  h2=@user.name
.content
  .row
    .col-lg-12
      .box
        .box-header.with-border
          h3.box-title= "Information"
        .box-body
          p
            strong Email
            = ": #{@user.email}"
          p
            strong Timezone
            = ": #{@user.time_zone}"
  .row
    .col-lg-12
      .box
        .box-header
          h3.box-title= "#{@user.name}'s' Standups"
  #user-standups-container
    = render partial: 'standups', locals: {standups: @standups}