config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resource :accounts
  resources :plans, only: [:index, :show]
  resources :subscriptions, only: [:create, :destroy]
  resources :cards, only: [:create]
  resources :billing, only: [:index] do
    collection do
      get 'change_card'
    end
  end
  resources :integrations, only: [:index] do
    collection do
      delete ':provider', action: 'destroy', as: 'remove'
    end
  end

  get 't/new', to: 'teams#new'
  get 't/:id/edit', to: 'teams#edit'
  get 't/:id/s', to: 'teams#standups', as: 'team_standups'
  get 't/:id/s/(:date)', to: 'teams#standups', as: 'team_standups_by_date'
  get 't/:id/(:date)', to: 'teams#show'
  resources :teams, path: 't'

  get 's/new/(:date)', to: 'standups#new', as: 'new_standup'
  get 's/edit/(:date)', to: 'standups#edit', as: 'edit_standup'
  resources :standups, path: 's', except: [:new, :edit]

  get 'user/me', to: 'users#me', as: 'my_settings'
  patch 'users/update_me', to: 'users#update_me', as: 'update_my_settings'
  get 'user/password', to: 'users#password', as: 'my_password'
  patch 'user/update_password', to: 'users#update_password', as: 'my_update_password'

  scope 'account', as: 'account' do
    resources :plans, only: [:index, :show], controller: 'accounts/plans'
    resources :users do
      member do
        get 's', to: 'users#standups', as: 'standups'
        get 's/(p/:page)', action: :standups
      end
    end
  end

  get 'activity/mine'
  get 'activity/mine/(p/:page)', to: 'activity#mine'

  get 'activity/feed'

  get 'dates/:date', to: 'dates#update', as: 'update_date'

  require "sidekiq/web"
  require 'sidekiq/cron/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest(ENV["SK_USER"])
    ) &
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(password),
      ::Digest::SHA256.hexdigest(ENV["SK_PASS"])
    )
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  # mount using default path: /email_processor
  mount_griddler

  mount StripeEvent::Engine, at: '/billing/events'

  # Webhooks
  post 'integrations/github/webhook/:team_id', to: 'events/github#create'

  root to: 'activity#mine'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role?(:user, user.account || Account.new)
      can [:me, :password, :update_me, :update_password, :standups], User
      can [:feed, :mine], ActivityController
      can [:index, :show, :standups], Team
      cannot :manage, Account
    elsif user.has_role?(:admin, user.account || Account.new) #is an admin
      can :manage, :all
    else
      can [:new, :create], Account
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  include Friendlyable
  resourcify
  has_many :users
  has_many :teams
  has_one :subscription
  has_one :github, class_name: Integrations::Github
  validates :name, presence: true
end

app/models/blocker.rb
class Blocker < Task

end

app/models/did.rb
class Did < Task

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/integration.rb
class Integration < ApplicationRecord
  belongs_to :account
end

app/models/plan.rb
class Plan
  def self.plans
    @plans ||= PLANS.keys.map { |k| PLANS[k] }
  end

  def self.all
    plans.map { |plan| OpenStruct.new(plan) }
  end

  def self.where(args)
    conditions = args.map do |arg_key, arg_val|
      proc { |plan| plan[arg_key] == arg_val }
    end
    local_plans = plans.select { |plan| conditions.all? { |c| c.call(plan) } }
    local_plans.flatten.map { |plan| OpenStruct.new(plan) }
  end

  def self.find(stripe_id)
    plan = plans.find { |p| p[:stripe_id] == stripe_id }
    OpenStruct.new(plan)
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/standup.rb
class Standup < ApplicationRecord
  include Friendlyable
  belongs_to :user

  validates :user, presence: true

  validates :standup_date, uniqueness: { scope: :user }

  has_many :task_memberships, dependent: :delete_all
  has_many :tasks, through: :task_memberships

  has_many :dids,
           -> { where(type: 'Did') },
           through: :task_memberships,
           source: :task
  accepts_nested_attributes_for :dids,
                                reject_if: :all_blank,
                                allow_destroy: true

  has_many :todos,
           -> { where(type: 'Todo') },
           through: :task_memberships,
           source: :task
  accepts_nested_attributes_for :todos,
                                reject_if: :all_blank,
                                allow_destroy: true

  has_many :blockers,
           -> { where(type: 'Blocker') },
           through: :task_memberships,
           source: :task
  accepts_nested_attributes_for :blockers,
                                reject_if: :all_blank,
                                allow_destroy: true
end

app/models/stripe_webhook.rb
class StripeWebhook < ApplicationRecord
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :account

  def active?
    %w(trialing active past_due).include?(status)
  end
end

app/models/task.rb
class Task < ApplicationRecord
  # belongs_to :user
  # validates_presence_of  :user

  validates_presence_of :title
  validates_presence_of :type

  has_many :task_memberships, dependent: :destroy
  has_many :standups, through: :task_memberships

  after_commit { standups.find_each(&:touch) }
end

app/models/task_membership.rb
class TaskMembership < ApplicationRecord
  belongs_to :task, optional: true
  belongs_to :standup, optional: true
end

app/models/team.rb
class Team < ApplicationRecord
  include Friendlyable
  belongs_to :account
  validates :account, presence: true
  validates :timezone, presence: true
  validates :name, presence: true

  has_many :team_memberships, dependent: :delete_all
  has_many :users, through: :team_memberships

  has_many :events

  has_many :days, class_name: 'DaysOfTheWeekMembership', dependent: :delete_all
  accepts_nested_attributes_for :days
end

app/models/team_membership.rb
class TeamMembership < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/todo.rb
class Todo < Task

end

app/models/user.rb
class User < ApplicationRecord
  include Friendlyable
  rolify
  attr_accessor :role
  belongs_to :account
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:github]
  has_many :team_memberships
  has_many :teams, through: :team_memberships
  has_many :standups

  def after_database_authentication
    Analytics::Mixpanel::IdentifyPersonJob.perform_later(self)
  end
end

app/controllers/billing_controller.rb
class BillingController < ApplicationController
  def index
    render :index and return if current_subscription.nil?
    begin
      @charges =
        Stripe::Charge.list(
          customer: current_subscription.stripe_customer_id
        ).data
    rescue Stripe::InvalidRequestError
      @charges = []
    end
  end

  def change_card; end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block alert-fixed">
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/billing/_cancel.html.slim
= form_tag subscription_path(current_subscription.stripe_subscription_id),\
  method: :delete do
    button.btn.btn-default{
      type='submit'
      disabled=(!current_subscription.active?)
      data={ confirm: 'Are you sure?' }}
        span
          | Cancel Subscription

app/views/billing/_card.html.slim
#card.content
  .row
    .col-lg-8.col-offset-lg-2
      .box
        .box-header
          h3.box-title Enter your card information:
        .box-body
          = form_tag(url_path, id: 'payment-form') do
            = (hidden_field_tag 'plan', params[:id]) if params[:id]
            .form-group
              .row
                .col-sm-12
                  label for="card-element"
                    |
                  #card-element style="border: 1px solid #d2d6de;padding: 2px;"
                  #card-errors role="alert"
            .form-group
              .row
                .col-sm-12
                  input{
                    type="hidden"
                    name="stripeToken"
                    id="stripeToken"
                  }
                  input{
                    name="cardholder-name"
                    id="cardholder-name"
                    class="field form-control"
                    placeholder="Name on Card"}
            = submit_tag\
              "#{params[:id].present? ? 'Submit Payment' : 'Update Card'}",\
              class: 'btn btn-default'

app/views/billing/change_card.html.slim
= render partial: 'billing/card',\
  locals: {url_path: cards_path}

app/views/billing/index.html.slim
#billing.content
  .row
    .col-sm-9.col-sm-offset-1
      .box
        .box-header.with-border
          h3.box-title Billing

  .row
    .col-sm-9.col-sm-offset-1
      .box
        .box-header.with-border
          h3.box-title Plan Information
        .box-body
          - if current_subscription&.active?
            p
              .pull-right
                = render partial: 'billing/cancel',\
                  locals: {subscription: current_subscription}
              = "Plan: #{current_subscription.plan_id.capitalize}"
              - if current_subscription.active?
                |  (
                a href="/plans"
                  | Change Plan
                |  )
            hr
            h4 Usage
            p
              = "Users: #{current_account.users.count}/\
              #{Plan.find(current_subscription.plan_id).users}"
            p
              = "Teams: #{current_account.teams.count}/\
              #{Plan.find(current_subscription.plan_id).teams}"
          - else
            p
              | There is no active plan on the account. To add one
              = link_to "click here.", plan_path('free')
          - if current_subscription&.card_last4.present?
            p
              .pull-right
                a.btn.btn-sm.btn-default{
                  href=change_card_billing_index_path}
                    | Change Card
              i.fa.fa-credit-card
              = " Payment: #{current_subscription.card_type} card ending in \
                #{current_subscription.card_last4} \
                Expiration: #{current_subscription.card_expiration}"
            hr
          - else
            a.btn.btn-sm.btn-default href=(change_card_billing_index_path)
              | Add Card
  .row
    .col-sm-9.col-sm-offset-1
      .box
        .box-header.with-border
          h3.box-title Plan Charge History
        .box-body
          table.table
            thead
              tr
                th Status
                th ID
                th Date
                th Amount
                th Description
                th Payment Method
            tbody
              - if @charges.blank?
                tr
                  td.text-center colspan="6"
                    | There are no charges on this account at this time.
              - else
                - @charges.each do |charge|
                  tr
                    td= charge.status
                    td= charge.id[3..-1]
                    td= Time.at(charge.created)
                    td= Money.new(charge.amount).format
                    td= charge.statement_descriptor
                    td= "#{charge&.source&.brand} #{charge&.source&.last4}"